### ISSUE TITLE
Source code compilation errors

### ISSUE THREAD

**Issue by muhammadawais95** [dem-net/DEM.Net#100]
Hi,
I am trying to compile the source code to run the `DEM.Net.TestWinForm` project.
I am getting the following errors. 

![Screenshot 2022-05-19 194915](https://user-images.githubusercontent.com/97820092/169326939-3ce02d4e-c937-4b58-b04d-e3ddcb0537b1.png)

Can someone please guide how to resolve them?

**Comment by xfischer** [comment]
Yes, I'm the one in charge here.
WinForms project is here for test purposes, I'll fix compilation, sorry about that.

What are you trying to achieve ?

**Comment by muhammadawais95** [comment]
Thanks for the quick response. I am trying to load a SRTM DEM file. Just wanted to run `DEM.Net.TestWinForm` to understand the working of the library.

**Comment by xfischer** [comment]
Build is fixed.
WinForms project is outdated, but if you want to give it a try, here's how :

![image](https://user-images.githubusercontent.com/2776898/169410455-e8c27662-16d1-48ed-b907-7ba5ee241836.png)

At step 2, the DEM files required to run the sample will be downloaded (a few seconds to wait).
At last step, a 3D file (.glb) will be generated under bin\debug\test3D

Let me know if you need more help.

**Comment by muhammadawais95** [comment]
Thank you @xfischer. It is now working. I also had a look at [samples](https://github.com/dem-net/Samples) and they helped a lot.
