### ISSUE TITLE
Quantized Mesh Terrain Tiles as Output format

### ISSUE THREAD

**Issue by geospatialmapmashup** [dem-net/DEM.Net#59]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to be able to have .terrain quantized mesh terrain tiles for use in CesiumJS and HarpGL in addition to gltf/glb export option.

**Describe alternatives you've considered**
Cesium Terrain Builder

**Additional context**
Very cool project
we are building mobile app Earth Explorer 3D Map App http://earthexplorer.world that supports both gltf/glb, 3DTiles and quantized mesh terrain tiles offline and streaming from the web.

**Comment by xfischer** [comment]
Hi! I’m trying to understand your needs. Why not using directly Cesium quantized meshes ? Or MapBox ? 
You want to superimpose elevation API models onto 3D tiles ? Is the resolution bad ?

**Comment by geospatialmapmashup** [comment]
Cesium costs $150/month minimum for Commercial use
So it's not an option

**Comment by xfischer** [comment]
So you want me to make a Cesium clone for free, for you, while you are selling your app $225 per user per year ?
Is this a paid job offer ??

BTW the back end server for elevationapi.com costs me 80€/month, and the service is __free__. This is the _option_ I chose.

I don't see an interest of doing __exactly__ what others do quite well. Tiling is great and is something I will do for sure, but at my own pace.
You're more than welcome to fork the repo and contribute.

Cheers!

**Comment by geospatialmapmashup** [comment]
I already processed the world I have mbtiles of quantized mesh terrain
tiles and area of interest tool dot net core tool
Served via my tile server or in app tile provider
Just giving users flexibility of other data sources

We use the data with cesium and harpgl/three js

Where are you getting $225 price ?
I will have three tiers on iOS, Android and Windows

Basic/lite, standard and Pro

The highest tier Pro is only $125/one time purchase not year

It supports every ESRI and OGC service and 3Dtiles and the gltf 3D Models

And SOCRATA,.CKAN, CSW open data

**Comment by geospatialmapmashup** [comment]
Let's arrange a Skype call would love to collaborate and work together
On different projects
We are doing Geo data Converter SaaS App

**Comment by xfischer** [comment]
I get the information from your site (didn't dive into other tiers)
I don't see how DEMNet terrain model would be a better option if you already processed the planet.
Sorry if I misunderstand your position. But I still not getting things straight here.

![image](https://user-images.githubusercontent.com/2776898/66720745-21259580-ee01-11e9-9f5b-9880fd7878e2.png)

**Comment by xfischer** [comment]
My skypeId is xfischer. Let's arrange a call tomorrow at 6PM paris Time

**Comment by xfischer** [comment]
You know what @geospatialmapmashup, this idea kept me thinking. 🤔 💭 ... Then I saw that quantized meshes were using RTIN [See article here](https://observablehq.com/@mourner/martin-real-time-rtin-terrain-mesh), and I definitely want to implement RTINs. So it's just a step before actually doing quantized meshes. Sorry for being rude, I better understand now that it's just an open standard and could be served as well from elevation api.
So let's reopen this one!

**Comment by xfischer** [comment]
Inactive. Closing
