### ISSUE TITLE
osgb to glb

### ISSUE THREAD

**Issue by 0mao0** [dem-net/DEM.Net#87]
Since this is most powerful landscapeModel->glb tool, I'd like to propose some idea.
Transfer OSGB  to glb, while most of the reality models are in this format?

preocedures might like this:
(1) extract the same Level of OSGB to the same folder(f1);
(2) merge all the osgb files in f1 into one osgb(osg1)
(3) transfer osg1 -> GeoTiff -> glb

**Describe alternatives you've considered**
osgb->obj->glb
looks the right way, but not working.

**Comment by xfischer** [comment]
Hi @0mao0, if I understand well, OSGB is the digital elevation model of Great Britain?
Would you be keen to work on that ?

**Comment by 0mao0** [comment]
> Hi @0mao0, if I understand well, OSGB is the digital elevation model of Great Britain?
> Would you be keen to work on that ?

Thanks for the quick reply.
It is my bad not explaining OSGB well.
OSGB  is one popular file format which applied in many GIS software. (B means binary, orginial file format is OSG)
https://filext.com/file-extension/OSGB

My idea is to expanding your work to the new scence.
looks like a whole new thing to you, and may interupt your plan on developing DEM.Net.
Sorrry for that if the idea is not ok.

**Comment by xfischer** [comment]
Thanks for the clarification. 
OSGB may be an option for _export_, but clearly not for import at the moment. 
I don't see how OSGB to GLB feature would fit into this project. I'm closing this. Feel free to reopen if you think this is relevant.
