### ISSUE TITLE
[0.2.9] Exception thrown when attempting to GetIntervisibilityReport.

### ISSUE THREAD

**Issue by rurounijones** [dem-net/DEM.Net#88]
Calling  `ElevationService.GetIntervisibilityReport` in release [0.2.9] results in the following _runtime_ exception

```
System.MissingMethodException: Method not found: 'Void NetTopologySuite.Geometries.LineString..ctor(GeoAPI.Geometries.Coordinate[])'.
   at DEM.Net.Core.GeometryService.ParseGeoPointAsGeometryLine(GeoPoint[] points)
   at DEM.Net.Core.ElevationService.GetIntervisibilityReport(GeoPoint source, GeoPoint target, DEMDataSet dataSet, Boolean downloadMissingFiles, Double sourceVerticalOffset, Double targetVerticalOffset, InterpolationMode interpolationMode)
```

I believe the issue is that the code in `GeometryService` is using `new Coordinate` without specifying if it is a `GeoAPI` Coordinate  or a `NetTopologySuite` one and the code is picking the wrong one at runtime. 

I believe this issue has been fixed in the master branch by the removal of GeoAPI as part of https://github.com/dem-net/DEM.Net/commit/b3d755f891778a69e9609c27ee57e989c21f9ee3

Is there a planned timeline for the next release of DEM.Net that contains this change?

Thanks for the great work and great library.

**Comment by xfischer** [comment]
Hi @rurounijones, thanks !

I'll try to make a new release by the end of the week. Thanks for reporting this :)

**Comment by rurounijones** [comment]
Wunderbar, thanks very much!

**Comment by xfischer** [comment]
@rurounijones Can you test now ?

**Comment by rurounijones** [comment]
No exceptions being thrown in [0.3.0]

Thanks for the quick support!
