### ISSUE TITLE
Weird line in GeoTIFF metadata parsing

### ISSUE THREAD

**Issue by galarlo** [dem-net/DEM.Net#96]
Hello,
I've noticed something weird in `GeoTiff.ParseMetadata`. I'm not sure whether it's a bug or if I missed something.
[In the following line](https://github.com/dem-net/DEM.Net/blob/263754d3559486b682315b512adc55f00b5f023f/DEM.Net.Core/IO/Raster/GeoTiff.cs#L280)
`double pixelSizeY = BitConverter.ToDouble(modelPixelScale, 8) * -1;` 
Why is the value multiplied by `-1`?

**Comment by xfischer** [comment]
Hi @galarlo.
Well imagine a GeoTIFF in lat/lon coordinates.
When X1>X2, you have Lon1>Lon2
But for Y : when Y1>Y2, then Lat1<Lat2, because latitude decreases when Y increases in that coord system.
And yes it's a bit hacky there, probaly needs to be read from GeoTiff tags (where ?) or set via parameters.

**Comment by galarlo** [comment]
Huge thanks for the fast reply!! 👍

However, one thing still doesn't make sense for me - [this line in `GeoTiff.GetHeightMap()`](https://github.com/dem-net/DEM.Net/blob/master/DEM.Net.Core/IO/Raster/GeoTiff.cs#L531):
`double latitude = metadata.DataStartLat + (metadata.pixelSizeY * y);`
Doesn't it mean that these latitudes will be smaller than `DataStartLat` (i.e. outside the bounds of the tiff)?
(In fact, I'm pretty sure that's what I see when I run my code)

**Comment by xfischer** [comment]
You may be right. Which GeoTiff file are you using ?
I had some hard time handling different registration modes (ie cell/grid, as explained here https://www.researchgate.net/figure/Differences-between-grid-registration-and-cell-registration-Grid-registered-grids-have_fig13_228077300)
I'll test again to see if everything is ok.

**Comment by fabric-io-rodrigues** [comment]
xfischer, excellent explanation.
A while ago, when I was looking for this one about GeoTiff, I found this blog that commented on Grid x Pixel, in the example the author exemplifies with -180, 90 pixel that corresponds to the coordinate -179.99166, 89.99166.

![image](https://user-images.githubusercontent.com/4131392/128712827-f96089d0-c5a2-48e9-b543-7f078adacf8a.png)
Source: http://build-failed.blogspot.com/2014/12/processing-geotiff-files-in-net-without.html

And I would like to thank you for your great work at DEM.Net!

**Comment by xfischer** [comment]
Still, @galarlo, if you have an issue, please provide your GeoTIFF so that I can run some tests and confirm your hypothesis.

**Comment by xfischer** [comment]
@galarlo , any news ?

**Comment by xfischer** [comment]
Please feel free to reopen the issue if needed
